export default `

//
// This file is automatically generated.
//
// Don't edit this file, and don't put it under version control!
//

import {IsoqRequestHandler} from $$ISOQ_SERVER$$;
import * as clientModule from $$CLIENT_MODULE$$;
let clientSource=$$CLIENT_SOURCE$$;

let requestHandlerInstance=new IsoqRequestHandler({
	clientModule: clientModule,
	clientSource: clientSource,
	...$$OPTIONS$$
});

let requestHandler=requestHandlerInstance.handleRequest;

export default requestHandler;
`;
