

//
// This file is automatically generated.
//
// Don't edit this file, and don't put it under version control!
//

import {IsoqRequestHandler} from "/home/micke/Repo/isoq/src/main/server-exports.js";
import * as clientModule from "/home/micke/Repo/isoq/examples/basic/public/client-ssr.js";
let clientSource=null;

let requestHandlerInstance=new IsoqRequestHandler({
	clientModule: clientModule,
	clientSource: clientSource,
	...{}
});

let requestHandler=requestHandlerInstance.handleRequest;

export default requestHandler;
